name: uber_clone
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  cloud_firestore: ^0.9.0
  firebase_auth: ^0.8.4+5
  firebase_database: ^2.0.3
  rxdart: any
  google_maps_flutter: ^0.5.19
  geoflutterfire: ^2.0.3+2
  location: ^2.3.5
  google_maps_webservice: ^0.0.14
  geolocator: any
  http: ^0.12.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true